getwd()
attach(lcd)
dim(lcd)
str(lcd)
class(lcd)
typeof(lcd)
names(lcd)
table(Smoke,Gender,Caesarean)
smoke_factor <- as.factor(Smoke)
smoke_factor
gender_factor <- as.factor(Gender)
caesarean_factor <- as.factor(Caesarean)
new_lcd<- data.frame(`LungCap(cc)`,`Age( years)`,`Height(inches)`,smoke_factor,gender_factor,caesarean_factor)
attach(new_lcd)
head(new_lcd,2)
str(new_lcd)
library(psych)
describe(new_lcd)
install.packages("e1071")
plot(Age..years.[smoke_factor =="no"], LungCap.cc.[smoke_factor =="no"], col="green", ylim=c(0,15), 
     xlim=c(0,20), xlab="Age", ylab="LungCap", 
     main="LungCap vs. Age,Smoke")
points(Age..years.[smoke_factor=="yes"], LungCap.cc.[smoke_factor=="yes"], col="red", pch=16)
legend(1,15,legend=c("NonSmoker", "Smoker"), col=c("green", "red"), 
       pch=c(1,16), bty="n")
mod1<- lm(LungCap.cc.~Age..years.)
abline(mod1,lwd=2,col="blue")
#hist(LungCap.cc.,main = "Normal Distribution for LungCap (cc)",xlab = "LungCap(cc)",ylab = "Count",breaks = 30,col = "grey" )
# Needs to identify the mistake curve(dnorm(LungCap.cc., mean = 0, sd = 1), 
#      col="darkblue", lwd=2, add=TRUE, yaxt="n")
l<-new_lcd$LungCap.cc.
hist(l,prob=T,main = "Normal Distribution for LungCap (cc)",xlab = "LungCap(cc)",ylab = "Count",breaks = 30,col = "grey" )
lung_norm = rnorm(length(LungCap.cc.),mean = (LungCap.cc.), sd = sd(LungCap.cc.))
lines(density(lung_norm, adjust = 2),col="Blue", lwd=0.5)

(table(smoke_factor)/length(smoke_factor))*100
table(smoke_factor, gender_factor)
cor(LungCap.cc.,Age..years.)
cor(LungCap.cc.,Height.inches.)
plot(Age..years.,LungCap.cc.,main="Relation between age and lung capacity"
     , col="violet",las=1, xlab="Age of the patient", ylab="Lung capacity")
abline(mod1,col=2,lwd=4)
count <- table(gender_factor)
percent <- table(gender_factor)/725
quantile(LungCap.cc.,probs = c(0,0.25,0.50,0.75,1))
agegroup<-cut(Age..years.,breaks = c(0.50,6.150,8.0,9.80,14.675),labels = ("Zero","<25%","","Q3","Q4"))
agegroup<-cut(new_lcd$Age..years.,breaks = c(3.0,9.0,13.0,15.0,19.0),labels = c("G1","G2","G3","G4","G5"))
my_label<-c("<3","Q1","Q2","Q3","18+")
agegroup<-cut(new_lcd$Age..years.,breaks = c(3,9,13,15,19),labels = c("0-3","4-9","10-13","14-19"),include.lowest = T)
agegroup[1:5]
boxplot(LungCap.cc.~smoke_factor*agegroup,main="LungCap Vs Smoke with comparison of Age",ylab="Lungcap vs smoke by age group",las=2,col=c(3,2))
boxplot(LungCap.cc.~gender_factor*agegroup,main="LungCap Vs Gender with comparison of Age",ylab="Lungcap vs Gender by age group",las=2,col=c(3,2))
boxplot(LungCap.cc.~caesarean_factor*agegroup,main="LungCap Vs caesarean with comparison of Age",ylab="Lungcap vs caesarean by age group",las=2,col=c(3,2))

# For Height
heightgroup<-cut(new_lcd$Height.inches.,breaks = c(20,40,60,80),labels = c("<20","21-40","41-60"),include.lowest = T)
heightgroup
boxplot(LungCap.cc.~gender_factor*heightgroup,main="LungCap Vs Gender with comparison of height",ylab="Lungcap vs Gender by height group",las=2,col=c(3,2))
boxplot(LungCap.cc.~smoke_factor*heightgroup,main="LungCap Vs Smoke with comparison of height",ylab="Lungcap vs Smoke by height group",las=2,col=c(3,2))
boxplot(LungCap.cc.~caesarean_factor*heightgroup,main="LungCap Vs caesarean with comparison of height",ylab="Lungcap vs caesarean by height group",las=2,col=c(3,2))
par(mfrow=c(1,2))
boxplot(LungCap.cc.~smoke_factor*agegroup,main="LungCap Vs Smoke with comparison of Age",ylab="Lungcap vs smoke by age group",las=2,col=c(3,2))
boxplot(LungCap.cc.~smoke_factor*heightgroup,main="LungCap Vs Smoke with comparison of height",ylab="Lungcap vs Smoke by height group",las=2,col=c(3,2))
boxplot(LungCap.cc.~gender_factor*agegroup,main="LungCap Vs Gender with comparison of Age",ylab="Lungcap vs Gender by age group",las=2,col=c(3,2))
boxplot(LungCap.cc.~gender_factor*heightgroup,main="LungCap Vs Gender with comparison of height",ylab="Lungcap vs Gender by height group",las=2,col=c(3,2))
boxplot(LungCap.cc.~caesarean_factor*agegroup,main="LungCap Vs caesarean with comparison of Age",ylab="Lungcap vs caesarean by age group",las=2,col=c(3,2))
boxplot(LungCap.cc.~caesarean_factor*heightgroup,main="LungCap Vs caesarean with comparison of height",ylab="Lungcap vs caesarean by height group",las=2,col=c(3,2))
plot(Age..years.,Height.inches.,main="Scatterplot Height vs Age",xlab="Age",ylab="Height",las=1,xlim=c(3,20),ylim=c(40,85),col=2,pch=5)
abline(lm(Height.inches.~Age..years.),col=5)
lines(smooth.spline(Age..years.,Height.inches.),lty=2,col=9)
plot(Age..years.,LungCap.cc.,main="Scatterplot Lung Cap vs Age",xlab="Age",ylab="Lung Cap",las=1,xlim=c(3,20),ylim=c(0,15),col=3,pch=3)
abline(lm(LungCap.cc.~Age..years.),col=2)
lines(smooth.spline(Age..years.,LungCap.cc.),lty=2,col=9)
plot(Height.inches.,LungCap.cc.,main="Scatterplot Lung Cap vs Height",xlab="Height",ylab="Lung Cap",las=1,xlim=c(45,82),ylim=c(0,15),col=1,pch=5)
abline(lm(LungCap.cc.~Height.inches.),col=2)
lines(smooth.spline(Age..years.,LungCap.cc.),lty=2,col=4)
qqplot(Height.inches.,LungCap.cc.,main="QQ plot between Lungcap vs Height")
summary(new_lcd)
str(new_lcd)
Names(new_lcd)
names(new_lcd)
fivenum(LungCap.cc.)
boxplot(`LungCap(cc)`[gender_factor =="female"], LungCap.cc.[gender_factor =="male"], col=c(2,4), xlab="Gender", ylab="LungCap", 
     main="LungCap vs. Gender",names = c("female","male"))
qqline(LungCap.cc.)
qqnorm(LungCap.cc.,main = "Normal QQ plot for LungCap")
qqline(LungCap.cc.,col=2)
qqline(Age..years.)
qqnorm(Age..years.,main = "Normal QQ plot for Age(Year)")
qqline(Age..years.,col=2,lwd=3)
qqnorm(Height.inches.,main = "Normal QQ plot for Height inches")
qqline(Height.inches.,col=2,lwd=3)
cor(LungCap.cc.,Age..years.,Height.inches.)
